services:
  rustfs:
    image: rustfs/rustfs:latest
    environment:
      RUSTFS_ACCESS_KEY: myuser
      RUSTFS_SECRET_KEY: mypassword
      RUSTFS_CONSOLE_ENABLE: "true"
    command: /data --console-enable --address ":9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./s3-data:/data
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://127.0.0.1:9000/health && curl -f http://127.0.0.1:9001/rustfs/console/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  createbuckets:
    image: minio/mc:latest
    depends_on:
      - rustfs
    entrypoint: >
      /bin/sh -c "
      mc alias set myrustfs http://rustfs:9000 myuser mypassword;
      mc mb myrustfs/dish-log || true;
      exit 0;
      "
